# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "m30"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"

engines:
   template_toolkit:
     encoding:  'utf8'
     start_tag: '[%'
     end_tag:   '%]'

serializer: 'JSON'
environment: 'development'

# gestion des sessions d'utilisateur dans la base de données
session: 'YAML'
session_name: session.money30
#A ajouter pour forcer l'envoie en ssl des cookies de sessions
#session_secure: true

# Sel de l'application - attention de ne pas perdre
# Longueur 16ocet / 23 caractères
salt: 'BIfoAOPaIBjYUc1yLfO3ou'

plugins:
    Database:
        connections:
                   asav:
                          driver:   'mysql'
                          database: 'asav'
                          host:     'localhost'
                          port:     3306
                          username: 'admin'
                          password: 'eliott'
                          connection_check_threshold: 10
                          dbi_params:
                                      RaiseError: 1
                                      AutoCommit: 1 
                          #on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
                          log_queries: 1

# Module support MultiLangue
############################  

    I18N:
        directory: I18N
        lang_default: fr


#ROLE BASE ACCESS CONTROLE avec Mysql
#Permet de manager les acces et les droits
    Auth::RBAC:
      permissions:
        class: Config
        options:
          control:
            admin:
              permissions:
                manage accounts:
                  operations:
                    - view
                    - create
                    - update
                    - delete
            user:
              permissions:
                manage accounts:
                  operations:
                    - view
                    - create
            guests:
              permissions:
                manage accounts:
                  operations:
                    - view
            prodige:
              permissions:

            client.ingenico:                      
              permissions:


      credentials:
        class: MySQL
        options:
         handle: asav
 

#    NYTProf:
#        profdir: '/home/money30/DancerM30/tmp'
#        nytprofhtml_path: '/usr/local/bin/nytprofhtml'



#IP du Serveur SMTP pour envoyer des emails
SMTP: '217.13.51.248'

# Chemin d'accès des fichiers temporaire pour le download
PUBLICTMP : '/home/svn/dancerM30/trunk/public/tmp/'

# Configuratation Taux de TVA 20.00% 
TVA : 0.2
